//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OficinaEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servico
    {
        public int Codigo_serv { get; set; }
        public string Placa_vei { get; set; }
        public int Codigo_tipo { get; set; }
        public System.DateTime DataInicio_serv { get; set; }
        public Nullable<System.DateTime> DataFim_serv { get; set; }
    
        public virtual TipoServico TipoServico { get; set; }
        public virtual Veiculo Veiculo { get; set; }
    }
}
