//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OficinaEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public Veiculo()
        {
            this.Servico = new HashSet<Servico>();
        }
    
        public string Placa_vei { get; set; }
        public string Modelo_vei { get; set; }
        public string Cor_vei { get; set; }
        public short Ano_vei { get; set; }
        public int Codigo_cli { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Servico> Servico { get; set; }
    }
}
